apiVersion : apps/v1
kind: Deployment
metadata:
  name: a2image 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: a2image
  template:
    metadata:
      labels:
        app: a2image 
    spec:
      containers:
        - name: a2image 
          image: a2registry.azurecr.io/a2image
          ports:
          - containerPort: 80